import './globals.scss'
import Head from "next/head";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    return (
        <html lang="en">
            <Head>
                <meta property="og:url" content="https://www.ugsm.co.kr/"/>
                <meta property="og:title" content="UGSM"/>
                <meta property="og:type" content="website"/>
                <meta property="og:image" content="https://code-study.tistory.com/images/img_share.png"/>
                <meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다."/>
            </Head>
        <body>{children}</body>
        </html>
    )
}
